name: Passing data between jobs
on:
  workflow_dispatch
jobs:
  addition:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > result.txt
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.txt
  display_result:
    needs: addition  # Doesn't start until addition job finishes
    runs-on: ubuntu-latest
    steps:
      - name: Download result
        uses: actions/download-artifact@v3
        with:
          name: result
      - name: Print the result
        shell: bash
        run: |
          value=`cat result.txt`
          echo The result is $value
