name: Script in workflow
on:
  workflow_dispatch
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greeting
        run: bash ./.github/scripts/greeting.sh
        env:
          NAME: Mona