name: Workflow secret
on:
  workflow_dispatch
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          learn_secret: ${{ secrets.LEARN_GITHUB_ACTIONS_SECRET }}
        run: |
          run: bash ./.github/scripts/echo_secret.sh
